name: Checkov Checks

on:
  pull_request:

jobs:
  preview:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkov
        run: |
          apt-get update && apt-get install -y python3-pip
          pip3 install checkov
          checkov -d .

# CKV_GCP* for GCP checks
# CKV2_GHA* for Github Actions checks
# CKV_GHA* for Github Actions checks
# CKV2_K8S* for Kubernetes checks
# CKV_K8S* for Kubernetes checks
# --skip-check CKV_GCP*,CKV2_GHA*,CKV_GHA*,CKV2_K8S*,CKV_K8S*
